##### Application properties #####
app.name=Gastro App
app.desc=Sistema gastronómico para gestión de mesas, pedidos y caja
app.version=1.0.0
app.url=http://localhost:8081
app.dev-name=Nicolas Nievas
app.dev-email=tu_email@gmail.com

server.port=8081

##### SPRING DOC #####
springdoc.packages-to-scan=com.example.gastro_app.controllers
springdoc.show-actuator=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/swagger-ui.html

##### PostgreSQL #####
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gastro_app}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

##### JPA #####
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true